name: Build RootBeer APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant gradlew execution rights
        run: chmod +x ./gradlew

      - name: Build APKs
        run: ./gradlew :app:assembleDebug :app:assembleRelease

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: RootBeer-APKs
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release-unsigned.apk
